One partition per virtual disk. Doc in comments. Plus less hardcoding.

diff --git a/Go b/Go
--- a/Go
+++ b/Go
@@ -1,5 +1,6 @@
 #!/bin/bash
 set -e -o pipefail
+shopt -s extglob
 
 
 ## [2019-11-19]
@@ -17,32 +18,33 @@ set -e -o pipefail
 
 function Create ()
 {
-	which VBoxManage
+	#which VBoxManage
 	
-	local tNow="$(cygwin-date +"%y%m%d-%H%M%S")"
+	local sVBoxManage="echo VBoxManage "
+	
+	
+	local tNow="$(date +"%y%m%d-%H%M%S")"
 	#local tUse="190925-141300"
 	local tUse="${tNow}"
-	echo "tNow ${tNow}, tUse {$tUse}..."
+	echo "## tNow ${tNow}, tUse {$tUse}..."
 	
-	local sName="${tUse}_Deborah"
+	local sName="${tUse}_SyndiVM"
 	
 	
 	
 	if ((1)); then
 		if [ -d "${sName}/" ]; then
-			echo "Unregistering \"${sName}\..."
-			set +e
-			VBoxManage unregistervm "${sName}"
+			echo "## Unregistering \"${sName}\..."
+			${sVBoxManage} unregistervm "${sName}"         || true
 			mv "${sName}/"          "${sName}_${tNow}"
-			set -e
 			echo
 		fi
 		
 		if true; then
-			echo "Creating machine \"${sName}\"..."
-			if   [ -d "${sName}/" ]; then echo "\"${sName}\" is already a folder !"; exit 1; fi
-			VBoxManage createvm --name "${sName}" --ostype "Debian_64" --register
-			if ! [ -d "${sName}/" ]; then echo "\"${sName}\" is not a folder !"    ; exit 1; fi
+			echo "## Creating machine \"${sName}\"..."
+			if   [ -d "${sName}/" ]; then echo "## \"${sName}\" is already a folder !"; exit 1; fi
+			${sVBoxManage} createvm --name "${sName}" --ostype "Debian_64" --register
+			#if ! [ -d "${sName}/" ]; then echo "## \"${sName}\" is not a folder !"    ; exit 1; fi
 			echo
 		fi
 	fi
@@ -50,16 +52,16 @@ function Create ()
 	
 	
 	if ((0)); then
-		echo "Showing..."
-		VBoxManage showvminfo "${sName}"
+		echo "## Showing..."
+		${sVBoxManage} showvminfo "${sName}"
 		echo
 	fi
 	
 	
 	
 	if ((1)); then
-		echo "Modifying..."
-		VBoxManage modifyvm "${sName}" \
+		echo "## Modifying..."
+		${sVBoxManage} modifyvm "${sName}" \
 			--memory                   2048          \
 			--vram                       32          \
 			--ioapic                   on            \
@@ -71,14 +73,14 @@ function Create ()
 			--clipboard                bidirectional \
 			--draganddrop              bidirectional \
 			\
-			--bioslogoimagepath        "Isabeau-1-cropped.bmp" \
+			--bioslogoimagepath        "Media/Isabeau-1-cropped.bmp" \
 			--boot1                    "none"        \
 			--boot2                    "dvd"         \
 			--boot3                    "disk"        \
 			--boot4                    "none"        \
 		
-		VBoxManage storagectl "${sName}" --name "IDE"  --add "ide"
-		VBoxManage storagectl "${sName}" --name "SATA" --add "sata"
+		${sVBoxManage} storagectl "${sName}" --name "IDE"  --add "ide"
+		${sVBoxManage} storagectl "${sName}" --name "SATA" --add "sata"
 		
 		echo
 	fi
@@ -86,8 +88,8 @@ function Create ()
 	
 	
 	if ((0)); then
-		echo "Showing..."
-		VBoxManage showvminfo "${sName}"
+		echo "## Showing..."
+		${sVBoxManage} showvminfo "${sName}"
 		echo
 	fi
 	
@@ -96,43 +98,68 @@ function Create ()
 	echo
 	
 	if ((1)); then
-		echo "Creating disks..."
+		echo "## Creating disks..."
 		
-		#VBoxManage storageattach "${sName}" --storagectl "IDE" --port "0" --device "0" --type "dvddrive" --medium "none"
+		#${sVBoxManage} storageattach "${sName}" --storagectl "IDE" --port "0" --device "0" --type "dvddrive" --medium "none"
 		
 		#sVariant="Split2G"
 		sVariant="Standard"
 		
 		local asDisks=()
 		{
-			asDisks+=("Root;32768")
-			asDisks+=("Swap;2048")
-			asDisks+=("Home;4096")
-			asDisks+=("DevKits;32768")
+			## [2020-08-24]
+			## 
+			##   Setup of storage:
+			##   
+			##     We are creating multiple 1-TiB disks.
+			##     No need to worry: VirtualBox is only going to save the part which is actually used.
+			##     
+			##     Each disk should have a single partition, initially of a much smaller size (e.g. 16 GiB or 32 GiB for the root partition).
+			##     
+			##     This is (I believe) a better setup than multiple partitions on a single disk:
+			##     it allows lean-and-mean backups
+			##     (including backups of individual partitions,
+			##     because they are reside on separate virtual disk files).
+			##     
+			##     This setup also allows us to grow the partitions easily when needed:
+			##     we can boot the virtual machine from a Linux optical disk image and (install and) run gparted
+			##     and increase the size of any partition (because there is space up to 1 TiB on the virtual disk).
+			##     
+			##     This setup also allows us to make the swap partition immutable:
+			##     its virtual disk need not occupy space when the virtual machine is powered off.
+			
+			asDisks+=("Root   ; 1048576; normal   ")     # 32768
+			asDisks+=("Swap   ; 1048576; immutable")     #  2048
+			asDisks+=("Home   ; 1048576; normal   ")     #  4096
+			asDisks+=("DevKits; 1048576; normal   ")     # 32768
 		}
 		
 		local iDisk=0
 		local sDisk
 		for sDisk in "${asDisks[@]}"; do
-			#echo "\"${sDisk}\""
+			#echo "## \"${sDisk}\""
 			local asSubDisks=()
 			{
 				IFS=";" read -r -a asSubDisks <<< "${sDisk}"
 				
-				#local sSubDisk
-				#for sSubDisk in "${asSubDisks[@]}"; do
-				#	echo "    \"${sSubDisk}\""
-				#done
+				if ((0)); then
+					local sSubDisk
+					for sSubDisk in "${asSubDisks[@]}"; do
+						local sSubDisk1="${sSubDisk}"
+						sSubDisk1="${sSubDisk1%%*( )}"
+						sSubDisk1="${sSubDisk1##*( )}"
+						printf "##     %-24s %-24s\n" "\"${sSubDisk}\"" "\"${sSubDisk1}\""
+					done
+				fi
 				
-				local sDiskName="${asSubDisks[0]}"
-				local sDiskSize="${asSubDisks[1]}"
-				printf "    %-16s %'9u\n" "${sDiskName}" "${sDiskSize}"
+				local sDiskName="${asSubDisks[0]?Bad entry in asDisks !}"; sDiskName="${sDiskName##*( )}"; sDiskName="${sDiskName%%*( )}"
+				local sDiskSize="${asSubDisks[1]?Bad entry in asDisks !}"; sDiskSize="${sDiskSize##*( )}"; sDiskSize="${sDiskSize%%*( )}"
+				local sDiskType="${asSubDisks[2]?Bad entry in asDisks !}"; sDiskType="${sDiskType##*( )}"; sDiskType="${sDiskType%%*( )}"
+				printf "##     %-16s %'9u %s\n" "\"${sDiskName}\"" "${sDiskSize}" "\"${sDiskType}\""
 				
-				set +e
-				VBoxManage closemedium  disk                                                 "${sName}/${sDiskName}.vmdk" --delete >/dev/null 2>&1
-				set -e
-				VBoxManage createmedium disk --format "VMDK" --variant "Standard" --filename "${sName}/${sDiskName}.vmdk" --size "${sDiskSize}"
-				VBoxManage storageattach "${sName}" --storagectl "SATA" --port "${iDisk}" --type "hdd" --medium "${sName}/${sDiskName}.vmdk" --mtype "normal"
+				${sVBoxManage} closemedium  disk                                                 "${sName}/${sDiskName}.vmdk" --delete >/dev/null 2>&1 || true
+				${sVBoxManage} createmedium disk --format "VMDK" --variant "Standard" --filename "${sName}/${sDiskName}.vmdk" --size "${sDiskSize}"
+				${sVBoxManage} storageattach "${sName}" --storagectl "SATA" --port "${iDisk}" --type "hdd" --medium "${sName}/${sDiskName}.vmdk" --mtype "\"${sDiskType}\""
 			}
 			
 			((++iDisk))
@@ -143,8 +170,13 @@ function Create ()
 	
 	
 	
-	echo "Hello, World !"
+	echo "## Hello, World !"
 }
 
-Create
-if [ $? -ne 0 ]; then echo "Error $? !"; fi
+function Main ()
+{
+	Create
+	if [ $? -ne 0 ]; then echo "## Error $? !"; fi
+}
+
+Main 2>&1 | tee _go
